### ISSUE TITLE
vgDrawGlyphs possibly not using adjustments properly

### ISSUE THREAD

**Issue by Gorggg** [Mazatech/amanithvg-sdk#1]
When a string of text is drawn with vgDrawGlyphs, it seems to be reading the adjustment values from the wrong locations in the provided array. For character 0, it is not using any adjustment value, only using the position set to VG_GLYPH_ORIGIN. For character 1, it uses the adjustment value in adjustments[0].

To demonstrate, if I had the following code:
```
VGuint indices[strlen];
VGfloat x_adjustments[strlen];
VGfloat y_adjustments[strlen];

for (int i = 0; i < strlen; i++) {

    /* Find computed values */

    indices[i] = computed_index;
    x_adjustments[i] = computed_x_adjustment;
    y_adjustments[i] = computed_y_adjustment;
}

vgSetfv (VG_GLYPH_ORIGIN, 2, overall_origin);
vgDrawGlyphs (font,
              strlen,
              indices,
              x_adjustments,
              y_adjustments,
              VG_FILL_PATH,
              VG_FALSE);
```

I would have to change it to this for it to use the adjustment value on character 0 and the correct adjustments on the following characters:

```
VGuint indices[strlen];
VGfloat x_adjustments[strlen];
VGfloat y_adjustments[strlen];

for (int i = 0; i < strlen; i++) {

    /* Find computed values */

    indices[i] = computed_index;
    x_adjustments[i] = computed_x_adjustment;
    y_adjustments[i] = computed_y_adjustment;
}

VGfloat[2] new_overall_origin = {overall_origin[0] + x_adjustments[0], overall_origin[1] + y_adjustments[0]};
vgSetfv (VG_GLYPH_ORIGIN, 2, new_overall_origin);
vgDrawGlyphs (font,
              strlen,
              indices,
              &x_adjustments[1],
              &y_adjustments[1],
              VG_FILL_PATH,
              VG_FALSE);
```

However, the specification does seem somewhat ambiguous about this, as it says: 

> The user space position of the first glyph (the point where the glyph origin will be placed) is determined by the value of VG_GLYPH_ORIGIN.

Contrary to one possible interpretation of that, it seems that many applications written against OpenVG use vgDrawGlyphs adjustments as if the 0th value will be used.

Thank you for taking the time to read this. If I could provide any more information, please let me know.

**Comment by muratmat** [comment]
OpenVG specifications are pretty clear:

_"The user space position of the first glyph (the point where the glyph origin will be placed) is determined by the value of VG_GLYPH_ORIGIN. vgDrawGlyphs calculates a new glyph origin for every glyph in the glyphIndices array by translating the glyph origin by the escapement vector of the current glyph, and applying the necessary positional adjustments, taking into account both the escapement values associated with the glyphs as well as the adjustments_x and adjustments_y parameters. Following the call, the VG_GLYPH_ORIGIN parameter will be updated with the new origin."_

So, the user space position of the first glyph is `VG_GLYPH_ORIGIN`. Then che "text cursor" will be updated by adding the glyph escapement (the one specified to the `vgSetGlyphToPath`) and adjustments (the ones specified to the `vgDrawGlyphs`). In pesudo code (taken from AmanithVG sources):

```
void glyphDraw(Context* context,
               const Glyph* glyph,
               const Vector2 adjustment) {
    // calculate the overall translation for the glyph
    Vector2 preTranslation = context->states[VG_GLYPH_ORIGIN] - glyph->origin;
    Matrix finalMatrix = context->matrices[VG_MATRIX_GLYPH_USER_TO_SURFACE] * TranslationMatrix(preTranslation);
    // draw the glyph path
    drawPath(glyph->path, finalMatrix);
    // update glyph origin within the OpenVG context
    context->states[VG_GLYPH_ORIGIN] += glyph->escapement + adjustment;
}

// vgDrawGlyphs pseudo-code
for (i = 0; i < glyphCount; i++) {
    // get glyph
    const Glyph* glyph = glyphGet(glyphIndices[i]);
    // get adjustments
    float adjX = (adjustments_x != NULL) ? adjustments_x[i] : 0.0f;
    float adjY = (adjustments_y != NULL) ? adjustments_y[i] : 0.0f;
    // draw the glyph
    glyphDraw(context, &glyph, Vector2(adjX, adjY));
}

```

This is the same schema used by the [Khronos OpenVG Reference implementation](https://github.com/KhronosGroup/OpenVG-Registry/blob/master/ri/openvg-1.1-ri.zip).

**Comment by Gorggg** [comment]
I see, that makes sense now. Thank you for the explanation, and sorry for taking your time.
